### ISSUE TITLE
InvalidOperationException: Added item does not appear at given index '1'

### ISSUE THREAD

**Issue by BentTranberg** [ReedCopsey/AdventTrees2016#3]
Add two trees. Decorate them. Light them. Click on one of them. Then the other.

InvalidOperationException: Added item does not appear at given index '1'

**Comment by ReedCopsey** [comment]
This is due to https://github.com/ReedCopsey/Gjallarhorn/issues/42 - Going to close to track there.

**Comment by FoggyFinder** [comment]
> Add two trees. Decorate them. Light them. Click on one of them. Then the other.

@BentTranberg I have not dig for now why it really happening but it could be related to "fake" updating collection. 

So, if you change the [line](https://github.com/ReedCopsey/AdventTrees2016/blob/master/TreeLogic/Forest.fs#L34) below:

```fsharp
| UpdateTree(msg, tree) -> Tree.update msg tree :: List.except [ tree ] forest
```

to

```fsharp
        | UpdateTree(msg, tree) -> 
            let upd = Tree.update msg tree
            if upd <> tree then
                upd :: List.except [ tree ] forest
            else 
                forest
```
exception won't fall because forest stay the same.
